name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install dependencies and run tests
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      # Build Docker image
      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }}
