name: Build and Push Docker Image to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install dependencies and run tests
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      # Build Docker image
      - name: Build Docker image
        run: docker build . -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Log in to Heroku Container Registry
      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      # Push Docker image to Heroku
      - name: Push Docker image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Release the container on Heroku
      - name: Release the Heroku container
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
